# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9974ae5f1f61d92b9c7f97bfbb7493bc4382e4ff1fc6e63472118031275af68609fa95c93414d412658a7f82f7956c402b5880c555c0020b20c0cafdeb4b33da

test:
  secret_key_base: 281a954b88e0654ffc180a5825cd3cf2c6703069c62d814840fd4f1e662c837a592aab805ce4a7a2b97abc0c5ea3b4904e18572dd1dc9430eb9e89be8ccea5c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
